version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=public
      - DB_SSL_MODE=disable
      - jwt_secret=secret
      - ENV=production
      - APP_NAME=project-esc
      - PORT=8080