database:
  driver: postgres
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  db_name: srs
  connections: 20

server: &server
  name: "Test Server"
  host: localhost
  port: 8084

redis:
  instances:
    redis: &redis
      driver: redis
      name: redis
      host: "localhost"
      port: 6379
      db: 0
  default: *redis

cache: *redis
session: *redis
storage: *redis

token:
  app_jwt_secret: SECRET_APP
  api_jwt_secret: SECRET_API
  expires_in: 3600
jwt:
  app:
    secret: SECRET_APP
    expire: 3600
  api:
    secret: SECRET_API
    expire: 3600

template:
  path: "resources/view"
  extension: ".django"

log:
  timefield: "timestamp"
  timeformat: "2006-01-02 15:04:05"
  graylog: &graylog
    host: localhost
    port: 12201
  file: &file
    path: "storage/logs"
    timeformat: "2006-01-02"
  console: &console
    level: "error"
    show: true
  info: *file
  warn: *file
  error: *file
  monitor: *graylog